Create profile
GDGPune-active/covid-gdgpune pull request #21
Opened 2021-05-19 14:32 UTC by amansaini7999

Created basic user profile on registering

2021-05-19 14:38 UTC, RonLek requested changes

2021-05-19 14:38 UTC, RonLek commented on server/createProfile/main.py
> +  'projectId': 'rustee-prod',
I think the project id should be taken from the env variables. Can replace with `<project_id>` **or** add a comment to let others know.

2021-05-19 19:08 UTC, amansaini7999 commented on server/createProfile/main.py
> +  'projectId': 'rustee-prod',
I have added a comment for others information

2021-05-20 13:58 UTC, RonLek approved these changes
LGTM!

2021-05-20 13:59 UTC, merged